# Generated by Django 3.0 on 2019-12-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('account', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
